CREATE DATABASE LibraryDB;


USE LibraryDB;


CREATE TABLE CATEGORY (
    CategoryID INT PRIMARY KEY IDENTITY,
    CategoryName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE BOOK (
    BookID INT PRIMARY KEY IDENTITY,
    Title NVARCHAR(150) NOT NULL,
    Author NVARCHAR(80),
    PublishYear INT,
    Available BIT DEFAULT 1,
    CategoryID INT NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

CREATE TABLE MEMBER (
    MemberID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(80) NOT NULL,
    Phone NVARCHAR(15),
    Email NVARCHAR(80) UNIQUE
);

CREATE TABLE STAFF (
    StaffID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(80) NOT NULL,
    Username NVARCHAR(40) UNIQUE,
    Password NVARCHAR(100) NOT NULL
);

CREATE TABLE LOAN (
    LoanID INT PRIMARY KEY IDENTITY,
    BookID INT NOT NULL,
    MemberID INT NOT NULL,
    StaffID INT NOT NULL,
    LoanDate DATE NOT NULL,
    ReturnDate DATE,
    Status NVARCHAR(10) NOT NULL DEFAULT 'Borrowed',
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON DELETE CASCADE,
    FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);
